CREATE TABLE "animals" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "date_of_birth" date NOT NULL,
  "escape_attempts" INT NOT NULL,
  "neutered" boolean NOT NULL,
  "weight_kg" decimal NOT NULL,
  "species" varchar(50) NOT NULL
);

CREATE TABLE "owners" (
  "owners_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar(100),
  "age" INT,
  "email" varchar(100)
);

CREATE TABLE "species" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100)
);

CREATE TABLE "vets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "age" int,
  "date_of_graduation" date
);

CREATE TABLE "specializations" (
  "vets_id" int,
  "species_id" int
);

CREATE TABLE "visists" (
  "vets_id" int,
  "id" int,
  "date_of_visit" date
);

CREATE INDEX "owner_index" ON "owners" ("email");

CREATE INDEX "vet_index" ON "visists" ("vets_id");

CREATE INDEX "visits_index" ON "visists" ("id");

ALTER TABLE "specializations" ADD FOREIGN KEY ("vets_id") REFERENCES "vets" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "specializations" ADD FOREIGN KEY ("species_id") REFERENCES "species" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "visists" ADD FOREIGN KEY ("vets_id") REFERENCES "vets" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "visists" ADD FOREIGN KEY ("id") REFERENCES "animals" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
